# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.CharField(max_length=3, unique=True)),
                ('status', models.CharField(choices=[('U', 'Urgente'), ('S', 'Stabile'), ('Z', 'Emergenza'), ('E', 'Eccedenza')], default='S', max_length=2)),
            ],
        ),
    ]
