# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(unique=True)),
                ('twitter_done', models.BooleanField(default=False)),
                ('facebook_done', models.BooleanField(default=False)),
                ('instagram_done', models.BooleanField(default=False)),
            ],
        ),
    ]
