# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_log_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='facebook_done',
        ),
        migrations.RemoveField(
            model_name='log',
            name='instagram_done',
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='status',
            field=models.CharField(choices=[('U', 'Urgente'), ('S', 'Stabile'), ('Z', 'Emergenza'), ('E', 'Eccedenza'), ('F', 'Fragile')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='log',
            name='image',
            field=models.ImageField(blank=True, upload_to='/Users/astagi/w/meteosangue/meteosangue/uploads/meteo/'),
        ),
    ]
