# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160810_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='telegram_done',
            field=models.BooleanField(default=False),
        ),
    ]
