# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_log_telegram_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='facebook_done',
            field=models.BooleanField(default=False),
        ),
    ]
