"""
Django settings for meteosangue project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os, sys

VERSION = '1.3.0'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False if os.getenv('PRODUCTION', '0') == '1' else True

ALLOWED_HOSTS = ['*']

SECRET_KEY = os.getenv('SECRET_KEY', 'S3KR3TK3Y_D3V')

FETCH_SITE_WAIT = int(os.getenv('FETCH_SITE_WAIT', 20))

ACCESS_TOKEN = os.getenv('ACCESS_TOKEN', 'D3V')
ACCESS_TOKEN_SECRET = os.getenv('ACCESS_TOKEN_SECRET', 'D3V')
CONSUMER_KEY = os.getenv('CONSUMER_KEY', 'D3V')
CONSUMER_SECRET = os.getenv('CONSUMER_SECRET', 'D3V')

TELEGRAM_TOKEN = os.getenv('TELEGRAM_TOKEN', 'D3V')
TELEGRAM_CHANNEL = os.getenv('TELEGRAM_CHANNEL', 'D3V')

FACEBOOK_TOKEN = os.getenv('FACEBOOK_TOKEN', 'D3V')

# Blood associations data

BLOOD_ASSOCIATIONS = [

    {
        'name': 'Avis Nazionale',
        'twitter_id': '@avisnazionale',
        'facebook_id': '154932917976132'
    },

    {
        'name': 'Avis Giovani',
        'twitter_id': '@giovaniavis',
    },

    {
        'name': 'Fidas Nazionale',
        'twitter_id': '@FIDASnazionale',
        'facebook_id': '49816054736'
    },

    {
        'name': 'Frates Nazionale',
        'twitter_id': '@FratresNaz',
    },

    {
        'name': 'Centro Naz. Sangue',
        'twitter_id': '@CentroSangue',
        'facebook_id': '477808612320970'
    }

]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

ENV_PATH = os.path.abspath(os.path.dirname(__file__))
UPLOAD_ROOT = os.path.join('meteosangue', 'uploads')
UPLOAD_METEO = os.path.join(UPLOAD_ROOT, 'meteo/')

BLOOD_FETCH_INTERVAL = 60 * 15

if 'test' in sys.argv:
    try:
        from .test_settings import *
    except ImportError:
        pass

