name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install phantomjs
          sudo apt-get --reinstall install -qq language-pack-it
          pip install -r requirements-test.txt
      - name: Run tests
        run: ./runtests.sh
      - name: Upload coverage
        uses: codecov/codecov-action@v2